
vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - mhutchie.git-graph
    - cweijan.vscode-database-client2
tasks:
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      exit
  - name: postgres
    init: |
      curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
      echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" |sudo tee  /etc/apt/sources.list.d/pgdg.list
      sudo apt update
      sudo apt install -y postgresql-client-13 libpq-dev
      exit
    command: |
      export GITPOD_IP=$(curl ifconfig.me)
      source "${THEIA_WORKSPACE_ROOT}/backend-flask/bin/rds/update-sg-rule"
      exit
  - name: frontend-react-js
    command: |
      cd frontend-react-js
      npm install
      cd $THEIA_WORKSPACE_ROOT
      exit
  - name: backend-flask
    command: |
      cd backend-flask
      pip install -r requirements.txt
      exit
  - name: fargate
    command: |
      curl "https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb" -o "session-manager-plugin.deb"
      sudo dpkg -i session-manager-plugin.deb
      rm session-manager-plugin.deb
      exit
ports:
  - name: frontend
    port: 3000
    visibility: public
    onOpen: ignore
  - name: backend
    port: 4567
    visibility: public
    onOpen: ignore
  - name: db
    port: 5432
    onOpen: ignore
  - name: dynamodb
    port: 8000
    onOpen: ignore